# Key bindings to control pipewire or pulseaudio volume with pactl.
# Displays a notification with the current state if /usr/bin/notify-send is available
#
# Volume increase/decrease step can be customized by setting the `$volume_step`
# variable to a numeric value before including the file.
# Maximum volume boost level can be set with the `$volume_limit` variable.
#
# Requires:     pulseaudio-utils
# Recommends:   libnotify

bindsym --locked {
    # XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5% && /usr/bin/notify-send "󰝝  Volume $(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)"
    # XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5% && /usr/bin/notify-send "󰝞  Volume $(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)"
    # XF86AudioMute    exec pactl set-sink-mute @DEFAULT_SINK@ toggle && /usr/bin/notify-send "󰖁  Mute Toggled"
    # XF86AudioMicMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle && /usr/bin/notify-send "󰍭  Microphone Mute Toggled"
    XF86AudioRaiseVolume exec ~/.config/sway/scripts/volumectl up
    XF86AudioLowerVolume exec ~/.config/sway/scripts/volumectl down
    XF86AudioMute        exec ~/.config/sway/scripts/volumectl mute
    XF86AudioMicMute     exec ~/.config/sway/scripts/volumectl micmute
}
