for_window [app_id="thunderbird"] mark floating_application
for_window [app_id="qalculate"] mark floating_application
for_window [app_id="qalculate-gtk"] mark floating_application
for_window [app_id="blueman-manager"] mark floating_application
for_window [app_id="nm-connection-editor"] mark floating_application
for_window [app_id="keepassxc"] mark floating_application
for_window [app_id="pavucontrol"] mark floating_application
for_window [app_id="pavucontrol-qt"] mark floating_application
for_window [app_id="lxqt-policykit-agent"] floating_application

for_window [con_mark="floating_application"] {
    floating enable
    move position center
}
