#  ____  _           _                ___        _               _
# |  _ \(_)___ _ __ | | __ _ _   _   / _ \ _   _| |_ _ __  _   _| |_
# | | | | / __| '_ \| |/ _` | | | | | | | | | | | __| '_ \| | | | __|
# | |_| | \__ \ |_) | | (_| | |_| | | |_| | |_| | |_| |_) | |_| | |_
# |____/|_|___/ .__/|_|\__,_|\__, |  \___/ \__,_|\__| .__/ \__,_|\__|
#             |_|            |___/                  |_|

# Monitor Outputs
set $first_output DP-1
set $second_output DP-2

# Resolution
output $first_output resolution 3840x2160@60Hz position 0,0
output $second_output resolution 3840x2160@60Hz position 3072,0

# Scaling
output $first_output scale 1.25
output $second_output scale 1.25

# Adaptive Sync
output $first_output adaptive_sync on
output $second_output adaptive_sync on

# Max Render Time
output $first_output max_render_time 1
output $second_output max_render_time 1

# Tearing
output $first_output allow_tearing enable
output $second_output allow_tearing enable

# Use GPU to draw mouse cursor
set $hardware_cursor yes
