# Default: all windows float
for_window [app_id=".*"]                   floating enable, move position center
for_window [class=".*"]                    floating enable, move position center

# Tiling windows
for_window [app_id="kitty"]                floating disable

# Floating windows (with Sizing and Centering)
for_window [app_id="thunderbird"]          floating enable, resize set 50 ppt 50 ppt, move position center
for_window [app_id="qalculate"]            floating enable, resize set 50 ppt 50 ppt, move position center
for_window [app_id="qalculate-gtk"]        floating enable, resize set 50 ppt 50 ppt, move position center
for_window [app_id="blueman-manager"]      floating enable, resize set 50 ppt 50 ppt, move position center
for_window [app_id="nm-connection-editor"] floating enable, resize set 50 ppt 50 ppt, move position center
for_window [app_id="keepassxc"]            floating enable, resize set 50 ppt 50 ppt, move position center
for_window [app_id="pavucontrol"]          floating enable, resize set 50 ppt 50 ppt, move position center
for_window [app_id="pavucontrol-qt"]       floating enable, resize set 50 ppt 50 ppt, move position center
for_window [app_id="claude-desktop"]       floating enable, resize set 50 ppt 50 ppt, move position center