workspace 1 output $first_output
workspace 2 output $first_output
workspace 3 output $first_output
workspace 4 output $first_output
workspace 5 output $first_output
workspace 6 output $second_output
workspace 7 output $second_output
workspace 8 output $second_output
workspace 9 output $second_output
workspace 10 output $second_output
