# __        __         _                                  
# \ \      / /__  _ __| | _____ _ __   __ _  ___ ___  ___ 
#  \ \ /\ / / _ \| '__| |/ / __| '_ \ / _` |/ __/ _ \/ __|
#   \ V  V / (_) | |  |   <\__ \ |_) | (_| | (_|  __/\__ \
#    \_/\_/ \___/|_|  |_|\_\___/ .__/ \__,_|\___\___||___/
#                              |_|                        

set $first_output "Samsung Electric Company LU28R55 HNMWC02779"
set $second_output "Samsung Electric Company LU28R55 H4ZR700824"
set $third_output "Lenovo Group Limited 0x8AB1 Unknown"

# Left External Monitor
workspace 1 output $first_output
workspace 2 output $first_output
workspace 3 output $first_output
workspace 4 output $first_output

# Right External Monitor
workspace 5 output $second_output
workspace 6 output $second_output
workspace 7 output $second_output
workspace 8 output $second_output

# Built-in Monitor
workspace 9 output $third_output
workspace 10 output $third_output
